name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: "andrija233/auction-svc"
            path: "src/AuctionService"
          - name: "andrija233/search-svc"
            path: "src/SearchService"
          - name: "andrija233/bid-svc"
            path: "src/BiddingService"
          - name: "andrija233/identity-svc"
            path: "src/IdentityService"
          - name: "andrija233/gateway-svc"
            path: "src/GatewayService"
          - name: "andrija233/notify-svc"
            path: "src/NotificationService"
          - name: "andrija233/web-app"
            path: "frontend/web-app"


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker 
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.service.path }}
        file: ${{ matrix.service.path }}/Dockerfile
        push: true
        tags: ${{ matrix.service.name }}:latest